spring.application.name=online-exam
server.port=${PORT:8080}

# PostgreSQL JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

file.upload-dir=./uploads/
