spring.application.name=online-exam
server.port=${PORT:8080}

# PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-red-mode-aikq5xzl.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=YOUR_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

# Hikari (optimized)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.initializationFailTimeout=0

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Performance
spring.main.lazy-initialization=true
spring.sql.init.mode=never

# Health check (IMPORTANT)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.db.enabled=true
management.server.port=${PORT:8080}
management.endpoints.web.base-path=/actuator

# File upload
file.upload-dir=./uploads
