spring.application.name=online-exam
server.port=${PORT:8080}

# PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-red-mode-aikq5xzl.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_73BqgvMJbIio
spring.datasource.driver-class-name=org.postgresql.Driver

# ✅ Hikari Fix (VERY IMPORTANT)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.initializationFailTimeout=0

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ✅ PERFORMANCE BOOST
spring.main.lazy-initialization=true

# ✅ HEALTH CHECK (VERY IMPORTANT)
management.endpoints.web.exposure.include=health

# File upload
file.upload-dir=./uploads/
